name: api-test-cybercube

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Rest-assured API Tests
        if: always()
        run: |
          cd api-tests
          mvn clean test 
        continue-on-error: true
