name: Cypress UI Test Cybercube

on: [ push ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies.
      - name: Cypress run
        uses: cypress-io/github-action@v4
        continue-on-error: true
        with:
          working-directory: e2e-ui-tests
          start: npx cypress run --browser electron
